model_name: "Qwen/Qwen3-30B-A3B-Instruct-2507"
use_lightweight_tokenizer: true
use_approximate_tokenizer: true

pg:
  pool_recycle: true
  pool_pre_ping: true

chat:
  max_failures: 3
  cooldown_seconds: 300
  models:
  - model_name: "Qwen/Qwen3-30B-A3B-Instruct-2507"
    endpoint_type: "openai"
    max_new_tokens: 3072
    timeout: 900

    chat_template_kwargs:
      enable_thinking: false

    # Sampling config
    # These two turned out best in our grid search:
    #
    #  `freq=0.2, min_p=0.10, pres=0.0`
    #
    # and
    #
    # `freq=0.6, min_p=0.05, pres=1.2`
    #
    # The second does better at quote quality.
    #
    # Subsequently found that:
    #
    # `freq=0.2, min_p=0.1, pres=1.2`
    #
    # Works better
    temperature: 0.7
    top_p: 1.0 # was 0.8
    top_k: -1
    min_p: 0.10
    presence_penalty: 1.2 # was 1.6
    frequency_penalty: 0.2
    repetition_penalty: 1.0


# Embedding Service Configuration
embedding:
  model: "BAAI/bge-small-en-v1.5"
  query_instruction: "Represent this sentence for searching relevant passages: "
  api_key: "dummy_key"
