"""init chat message schema

Revision ID: a85211bff985
Revises: 
Create Date: 2026-02-27 17:46:35.868898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a85211bff985'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_message',
    sa.Column('message_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('message_id', name=op.f('pk_chat_message'))
    )
    op.create_index(op.f('ix_chat_message_chat_id'), 'chat_message', ['chat_id'], unique=False)
    op.create_table('chat_message_part',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('part_id', sa.Text(), nullable=False),
    sa.Column('part_type', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_message.message_id'], name=op.f('fk_chat_message_part_message_id_chat_message'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'part_id', name=op.f('pk_chat_message_part'))
    )
    op.create_index('ix_chat_message_part_message_id_ordinal', 'chat_message_part', ['message_id', 'ordinal'], unique=False)
    op.create_index(op.f('ix_chat_message_part_part_type'), 'chat_message_part', ['part_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_message_part_part_type'), table_name='chat_message_part')
    op.drop_index('ix_chat_message_part_message_id_ordinal', table_name='chat_message_part')
    op.drop_table('chat_message_part')
    op.drop_index(op.f('ix_chat_message_chat_id'), table_name='chat_message')
    op.drop_table('chat_message')
    # ### end Alembic commands ###
